### ISSUE TITLE
Ordering information is kept in a slice_map in the data_proxy object

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fsttable#25]
A slice map would be implemented as an `unsigned int` or `unsigned long long` vector (depends on the size of the table). The length would be equal to the number of selected elements in the mask.

This vector can be large: a 1 billion row selection will have a slice map of 4 GB (`unsigned int`). A 5 billion row selection will have slice map of 40 GB (`unsigned long long`). So these maps are potentially too large for the user's memory and might require storing on-disk.

Ordering is expensive. But for printing purposes, where we need only 10 rows, at most 10 complete (16 kB) blocks have to be read. That's no problem because that should be sub-millisecond reads for each column (so no need to read the whole column for table's with a stored _slice map_)

**Comment by martinblostein** [comment]
To aid discussion, I've implemented a very naive version of the slice_map (and row_filter) completely in R and submitted it as a PR.

Based on doing that quick implementation, I have some thoughts, but I need to collect them. One observation:
- As written/implemented, I don't believe this can support row selections with repeated indices as `data.table` can (i.e: `ft[c(1,2,2,1)]`. We could decide to simply not support that behaviour, or handle it with a different structure.

**Comment by martinblostein** [comment]
For a table with `N` rows, and `S <= N` selected columns, we have a length-`N` binary row filter which determines which rows are included, and a length-`S` integer vector with elements in `1:S`, that determines their permutation.

The same information could alternatively be encoded in a single length-`S` integer vector with elements in `1:N`. This would allow us to handle selections with repeated rows, and it seems it would also be more convenient for accessing subsets of the remote table. For example, when you need the first 5 rows of a table for printing, you read the first 5 elements from this vector, and you have the corresponding indices of the rows on disk. With the slice_map + row_filter, the procedure is less obvious. (Unless I am missing something!) 

I'm less clear on the advantages of separating the row ordering & selection, although I am certain there are many. Interested to hear your thoughts!

**Comment by MarcusKlik** [comment]
thanks! You're absolutely right, there is no extra information in the binary row-filter as compared to just the permutation integer vector, it's just to enhance speed and reduce size.

In `fst`, each block of on-disk data is 16 kB in size (e.g. 4096 integers). That block has to be read in full because it's (usually) compressed and might have other transformations that only work on complete blocks (like bit shifting). So to read at maximum speed, it would be best to have a selection vector that has a structure with multiple layers:

* a binary vector with 1 bit per row
* a binary vector with 1 bit per block
* a binary vector with 1 bit per _N_ blocks
* a binary vector with 1 bit per _N * N_ blocks
* ...

with this setup, a mask could be parsed very efficiently. For example, when only a few bits are set, and _N_ is equal to 16, `fst` can quickly drill down to the required blocks by zooming in with a factor of 16 in each 'zoom' step. Also with the first binary vector, elements can be selected very efficiently (in C++) by iterating the bits in each block (although for sparse selections, the permutation vector would be more efficient). Also, the binary vector can be stored by `fst` in a separate file at high speed.

When we start with a permutation vector, a full read would require the following steps:

* determine the row-mask defined above
* calculate the inverse-permutation vector. So for each element read (using the mask) that vector would contain the index of the target element in the result vector (this is an expensive ordering task).

With those two vectors, the reads can be sequential while the memory stores could be random. That's much faster than random reads with sequential memory stores.

As you say, we would need to think of some scheme to store repeated elements. Perhaps we can use the high bit of the inverse-permutation vector to signal whether the element is unique or has to be copied to more output elements (so 1 bit for two states). The inverse permutation vector would then be equal in length to the permutation vector and might contain duplicate element (but this is just me free thinking :-)). Another option would be to calculate a map for each block with an index vector into the block and a output index vector into the result vector. That would solve the duplicate problem.

I guess to have the fastest access times, we need to store both the inverse permutation vector and the row mask (at least at block level) or block-map. Maybe those structures should be defined in the _remote table_ so that implementations can think of the best way to store the information for that specific back-end...

**Comment by martinblostein** [comment]
Thanks for the thorough comments! I think we are focusing on different sides of things.

I see how the binary vector is a convenient format for the `fst` backend. However, I still don't think it is particularly convenient for printing or updating the state of the `proxy_table`. As you say here:

> Maybe those structures should be defined in the remote table so that implementations can think of the best way to store the information for that specific back-end...

I think if it is designed with `fst` in mind, it should indeed go in the `fst` implementation of `rtable`. 

Furthermore, the binary filter doesn't have a corresponding method in the `rtable` interface, which currently only has methods for reading ranges of columns (same `fst`). So perhaps the `rtable` interface needs to be expanded, in preparation for when `fst` is ready to accept binary filters.

--- 

To be concrete, say the user has created a `fst_table` of and manipulated it so that the first 5 rows of the table correspond to rows (6, 5, 10, 1, 2) on disk. (I'm sticking with R indices for this example.) If I understand the `row_filter`/`slice_map` correctly, this selection would be represented in the `table_proxy` as:

```
# State Scheme A
# slice_map[i] is memory-row of i-th rank disk-row
# i.e. slice_map = order(6, 5, 10, 1, 2)
row_filter = (1, 1, 0, 0, 1, 1, 0, 0, 0, 1, ...)
slice_map = (4, 5, 2, 1, 3)
```
Or, if the slice_map is inverted:
```
# State Scheme B
# slice_map[i] is disk-row rank of i-th memory-row
# i.e. slice_map = rank(6, 5, 10, 1, 2)
row_filter = (1, 1, 0, 0, 1, 1, 0, 0, 0, 1, ...)
slice_map = (4, 3, 5, 1, 2)
```
Alternatively we could have this:
```
# State Scheme C
# disk_rows[i] is disk-row of i-th memory-row
disk_rows = (6, 5, 10, 1, 2)
```

Whether or not these are stored literally in the `table_proxy` object or on disk isn't important -- the point is that these vectors have to be in sync with the state of the `table_proxy`. 

Say the user now selects rows (1, 3, 5). This could be as a result of a condition (i.e. `i = Sex != Male`) or explicit selection `i = c(1,3,5)`. To update the state:

Under `A`, we find 1, 3, and 5 in the `slice_map`. We note their indices (4, 5, 2) and update the slice_map to be their ordering permutation (2, 3, 1). We then have to locate the 2nd, 4th and 5th nonzero values in `row_filter`, (positions 2, 5, 10), and zero out everything except those values.

The procedure under `B` is similar. We read from indices 1, 3, and 5 in the `slice_map` and note their values (4, 5, 2). We update the slice map to be the the inverse permutation (2, 1 ,3). As above, we then have to locate the 2nd, 4th and 5th nonzero values in `row_filter`, (positions 2, 5, 10), and zero out everything except those values.

Under `C`, we just update `disk_rows` to be array elements (1, 3, 5) of `disk_rows`. 

---

The above operation ought to be quick and efficient, as it doesn't require reading anything from the actual `fst` file. I propose is that we represent state within `table_proxy` using representations that are simple for updating and fulfilling small queries, and create structures optimized for reading on the fly.

**Comment by martinblostein** [comment]
Ah I've just seen some new commits,, looks good!

**Comment by MarcusKlik** [comment]
Hi @martinblostein, that's a great analysis of the current setup and your idea about keeping just a small representation (for printing) is very good, thanks!

And you're absolutely right, the `row_filter` is useful for `fst` but might not be useful for other back-ends. For example, if the backend is a very fast database server, keeping just the `slice_map` will be enough. So the `row_filter` is probably best stored in the _remote table_, if required.

In these last commits, I removed the `row_filter` completely (but it will probably re-surface in the `remote_table_fst` object :-))

**Comment by MarcusKlik** [comment]
Shall we close this issue now that we have the `slice_map` implemented?

**Comment by martinblostein** [comment]
Yes, and #24 as well.

**Comment by MarcusKlik** [comment]
Just one more more thought on the `row_filter` vs. `row_filter` + `row_mask` discussion:

The only reason for storing a `row_mask` is to skip the expensive ordering that has to be done on the (potentially random) `row_filer` before data can be read sequentially. Most back-ends will have such a sequential ordering, so using a `row_filter` will be slower than using a `row_mask` in general.

But instead of storing both, we can just add a logical field to the `remote_table_state` that indicates whether the `row_filter` is ordered. An ordered `row_filter` can be processed almost as efficiently as a row-mask and for very sparse selections, probably even more efficiently (see #31). With that, there is no need for a binary filter anymore :-)
